### ISSUE TITLE
USER STORY: Create Event Page

### ISSUE THREAD

**Issue by TroyFPV48** [SeattleColleges/nsc-events-nextjs#204]
As a developer, I want to have the event page to be enhanced and follow the client's needs:
- [x] Remove the event website and cost fields.
- [x] Under the event location field, add an input field for Event Meeting URL
- [x] Add the following tags: Cultural, Study, Coffee, Free Food, Craft, Art/Creative, and Club.
- [x] Add a note field (last input field on page)

**Comment by heosman** [comment]
@TroyFPV48 What's your progress on this user story? I noticed that you haven't created an issue or branch yet.

**Comment by TroyFPV48** [comment]
> @TroyFPV48 What's your progress on this user story? I noticed that you haven't created an issue or branch yet

I haven't created an issue and branch but it's almost ready, everything will be pushed right after I create them. Thanks for the reminder.
