### ISSUE TITLE
USER STORY: MISC

### ISSUE THREAD

**Issue by JesseCaddell** [SeattleColleges/nsc-events-nextjs#250]
As an Admin, I want to the "View All Events" button to rout to the Home Page. As a Creator, I want the "View All Events" button to route to the Home Page. As a User, I want to view the Home Page after I sign in.

Issues:
- [x] #266
- [x] Creator Page: Route the "View All Events" button to the Home page
- [x] #267

![Image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/80575182/577af335-90ac-4f35-a6bc-61ecb2917094)
Admin Page routing

![Image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/80575182/aeff22e1-5095-4f7c-a9ec-2c9508050996)
Creator Page routing

![Image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/80575182/4d1c38e2-8862-4be1-8bc7-bfe63ff13d59)
User Login routing

**Comment by JesseCaddell** [comment]
@heosman Can we reopen this story? I have one more issue to complete

**Comment by heosman** [comment]
> @heosman Can we reopen this story? I have one more issue to complete

No problem. Make sure to create issues for your tasks and to mention _those_ issues in your PR (when saying Resolves #), rather than the user story. That way your user story won't close when your PR is merged.

**Comment by themidgargospel** [comment]
> > @heosman Can we reopen this story? I have one more issue to complete
> 
> No problem. Make sure to create issues for your tasks and to mention _those_ issues in your PR (when saying Resolves #), rather than the user story. That way your user story won't close when your PR is merged.

Awesome, thanks for that clarification!
