### ISSUE TITLE
USER STORY: Nav Bar

### ISSUE THREAD

**Issue by miqo1385** [SeattleColleges/nsc-events-nextjs#285]
- As a developer, I will want to work on these tasks:
- [x] Change “Home” to “Events”
- [x] Remove “Dashboard” link and "Sign out" button
- [x] Add a profile icon (similar to [Belinda’s Closet android app](https://github.com/SeattleColleges/belindas-closet-        android/pull/278/)), which when clicked, opens a drop down menu with  a “Profile link” and "Sign Out" link
- [ ] The Profile link should route to the admin page if user is admin or the creator page if the user is a creator
- [x] Sign Out link should be working

**Comment by heosman** [comment]
Closing since we no longer use user story issues.
