### ISSUE TITLE
Feature: Arrow Icons on Event Detail Page

### ISSUE THREAD

**Issue by nwm516** [SeattleColleges/nsc-events-nextjs#295]
Relates to #293 

- [x] Add arrow icons to the left and right side of the event.
- [ ] When the right arrow is clicked, the event being displayed switches to the next one. If there are no more events, the right arrow should disappear.
- [ ] When the left arrow is clicked, the event being displayed switches to the previous one. If there are no more previous events, the left arrow should disappear.

![Image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/36825393/d113fdbd-e2f4-4ec7-9d14-7033824519f6)

**Comment by heosman** [comment]
@nwm516 Just checking in, what's your progress on this issue?

**Comment by nwm516** [comment]
@heosman Hi Hanan, thanks for checking in. This has proven to be more difficult for me than I realized it would be. I have sample events, login credentials, etc. created with Postman and MongoDB but seem to get caught up on how the events are being loaded in. I've tried gleaning some information from the ViewMyEventsComponent that the home page uses to load events in but I am not really sure if this is something I will be able to reasonably finish at this current state of my know-how.


https://github.com/SeattleColleges/nsc-events-nextjs/assets/36825393/7587b41c-472f-4d5c-9c23-1ad6b3d5d955

**Comment by heosman** [comment]
> @heosman Hi Hanan, thanks for checking in. This has proven to be more difficult for me than I realized it would be. I have sample events, login credentials, etc. created with Postman and MongoDB but seem to get caught up on how the events are being loaded in. I've tried gleaning some information from the ViewMyEventsComponent that the home page uses to load events in but I am not really sure if this is something I will be able to reasonably finish at this current state of my know-how.
> 
>  NSC.Event.Details.Page.mp4

@nwm516 If you feel that this issue is too difficult for you to complete on your own, you can unassign yourself from this issue and other developers may be able to pick up where you left off. I can see that you've made some changes, like adding the arrow buttons, so you can create a PR for that and then move on to your other issues. Let me know what you'd like to do.

**Comment by nwm516** [comment]
> > @heosman Hi Hanan, thanks for checking in. This has proven to be more difficult for me than I realized it would be. I have sample events, login credentials, etc. created with Postman and MongoDB but seem to get caught up on how the events are being loaded in. I've tried gleaning some information from the ViewMyEventsComponent that the home page uses to load events in but I am not really sure if this is something I will be able to reasonably finish at this current state of my know-how.
> > NSC.Event.Details.Page.mp4
> 
> @nwm516 If you feel that this issue is too difficult for you to complete on your own, you can unassign yourself from this issue and other developers may be able to pick up where you left off. I can see that you've made some changes, like adding the arrow buttons, so you can create a PR for that and then move on to your other issues. Let me know what you'd like to do.

@heosman Yes, I will move forward stepping away from this issue. I will create a new PR with the work I have done as a part of it and it allow another developer to take on this task. Thank you for laying out how I should go for in this situation.
