### ISSUE TITLE
USER STORY: Figma Sitemap/userflow diagram

### ISSUE THREAD

**Issue by IsaacJrTypes** [SeattleColleges/nsc-events-nextjs#301]
As a developer, I want a high fidelity site map to better understand the website's flow. The diagram should reflect the current and ongoing state of the app.

- [ ] Use Figma to create a diagram of all of our pages and how users can navigate.

**Comment by IsaacJrTypes** [comment]
Here Are the Figma user flow and page wireframes of NSC Events in its current state.
Please feel free to give me any feedback. I can also supply the figjam file and link to the project.
[NSC-Events-User-Flow(Current).pdf](https://github.com/SeattleColleges/nsc-events-nextjs/files/15343479/NSC-Events-User-Flow.Current.pdf)
[NSC-Events-Wireframe.pdf](https://github.com/SeattleColleges/nsc-events-nextjs/files/15343480/NSC-Events-Wireframe.pdf)

**Comment by Robel-003** [comment]
NSC Events figma diagram feedback: 

* Diagram looks accurate to the flow of the application
* For users of the application that are not admin or creator, is there a path for them? Would they just see all the public events?
* I think there’s an edit user role page that allows a user to edit roles, would that be another input below the the “Edit User Role” page/process
* Minor things to consider:
    * I know this is high level diagram but would an another path for when a user signs up or resets their password help?
    * Another thing to consider is the edit functionality in the event view card, which could be another input legend, would that addition help?

**Comment by IsaacJrTypes** [comment]
Thank you for the feedback! You bring up great points. I will look into addressing the issues you raise.
