### ISSUE TITLE
USER STORY: Responsive UI

### ISSUE THREAD

**Issue by Robel-003** [SeattleColleges/nsc-events-nextjs#413]
As an developer, I want to be able to view the nav bar hamburger menu when the screen is between 600px and 900px widths. At the moment, the page crops out the hamburger menu and parts of the screen when the window is shrunk. I want to adjust the styling of the page so page elements on all pages are not broken or cropped or off-screen for mobile screens.  

Issue:
- [x] #414

<img width="503" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/116779961/197fac46-6199-43be-b810-3e7e2d94f01d">

<img width="502" alt="image-2" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/116779961/66de1e55-ae06-4509-8ab3-3db3648385ec">

**Comment by heosman** [comment]
Closing since we no longer use user story issues.
