### ISSUE TITLE
Bug: Missing requirements for creating new event stay visible after corrected

### ISSUE THREAD

**Issue by JesseCaddell** [SeattleColleges/nsc-events-nextjs#436]
When creating a new event if you do not fill the required boxes you are presented with red text telling you what you need to complete. When you correct those errors, they stay on the screen even after the event is successfully created.

Adding additional issue noticed within the same bug. Event Privacy is required and you get a prompt that it should not be left empty, yet there is no red outline around Event Privacy and no red text saying Event Privacy is required.

Additional notes via Hanan:
I also noticed that some fields are optional but still require you to fill out the field and vice versa (like Event Note). The error handling for all of the fields should match on the frontend and the backend. 

**To Reproduce**\
Create an event
Leave fields blank
Once red text shows up, complete all required forms
Click create event

**Expected behavior**\
Red text should disappear when the form required is corrected

**Screenshots**\
red text not veing removed
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/80575182/6985b5af-29a9-4c4d-a1e6-c7c65c836907)
Event Privacy
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/80575182/af25e336-d268-4bad-859c-c389eeaf6d79)

**Desktop (please complete the following information):**\
 - OS: Windows
 - Browser: Firefox
 - Version 126.0.1

**Is this issue related to any other issues?**\
Not that I am aware of

**Story Points**\
maybe 2

**Comment by heosman** [comment]
@JesseCaddell Thank you for picking up on this! I also noticed that some fields are optional but still require you to fill out the field and vice versa (like Event Note). The error handling for all of the fields should match on the frontend and the backend. Since this is related to the same bug, feel free to address this also in this issue!

**Comment by cshimm** [comment]
I can take this one on
