### ISSUE TITLE
Update theme background color for light mode

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/nsc-events-nextjs#443]
Tasks:
- [x] Change theme background color in light mode from cream to white/light grey 
- [x] Heading text has consistent styling on all pages
- [x] Make sure text has proper contrast in dark mode (ex. Home Page, Create Event page, Sign In page)

**Comment by tinpham5614** [comment]
I'm not sure if you're addressing this issue, but the text color on the home page is barely visible with a dark color.
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/72054441/366dd26b-673e-4aa5-9b54-14e619c44b3e)

Removing line 60 in home.module.css will resolve this.
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/72054441/c8d90d3c-bfad-4b15-b250-57ba7203a010)

Let me know if you need me to work on this.

### Result:
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/72054441/2dd32f1f-4d7c-4561-bccd-3a92ccbc6cf0)
![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/72054441/b07f450a-8e38-4f87-a2ec-15b8210e90b7)

**Comment by heosman** [comment]
@tinpham5614 Thanks for the heads up! I'm currently working on making the text on the Home page have better contrast in dark mode, but I haven't pushed the changes yet.
