### ISSUE TITLE
Home Page: Add Mascot Image

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/nsc-events-nextjs#474]
As a developer, I want to:

- [ ] Add NSC mascot image above the upcoming event on the right side 

![image](https://github.com/SeattleColleges/nsc-events-nextjs/assets/77607212/73ee0ad6-db84-4d3f-8774-2d0f6838b42e)

**Comment by nhapham03** [comment]
Hey @intisarosman1, I have already got this resolved.
