### ISSUE TITLE
BUG: URL errors when editing event 

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/nsc-events-nextjs#501]
When editing an event, the Event Cover Photo and Event Meeting URL fields have errors despite being filled in correctly.

<img width="468" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/5d51b37e-6ac2-494d-8923-f3e20f2b427a">

<img width="307" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/3d0827c0-75d1-4043-82eb-75c444c1fce4">

**Comment by ken-ni** [comment]
@heosman I can help with fixing this bug

**Comment by heosman** [comment]
> @heosman I can help with fixing this bug

@ken-ni Great! 

@cshimm solved a similar issue in [this PR](https://github.com/SeattleColleges/nsc-events-nextjs/pull/480) so feel free to take a look.
