### ISSUE TITLE
BUG: Fix "Loading..." when clicking an event that is archived

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/nsc-events-nextjs#508]
When an event on the Archived Events page is clicked, the user is routed to the Event Detail page, but the event card is not rendered.

<img width="750" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/e1c4a724-ea71-4e18-818d-7920dd3cef5e">

**Comment by cshimm** [comment]
I can fix this one @heosman
