### ISSUE TITLE
BUG: Fix errors for Start Time and End Time fields in Edit Event dialog

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/nsc-events-nextjs#518]
1. When editing an event, start time and end time fields have a red outline as if there is an error, when there is none. It does not affect the changes being saved, but it should be fixed to avoid confusion. 
<img width="500" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/af88ddb9-9fc7-4959-80d1-41f915ce73a9">

2. In addition, these two fields should display the time that was set previously for the event, rather than "hh:mm aa" like it does currently. This is what it should look like:
<img width="500" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/0d1cb677-5c8c-46c8-8ed5-20f6e37b2166">

**Comment by cshimm** [comment]
I will pick this up @heosman
