### ISSUE TITLE
Update an Event UI

### ISSUE THREAD

**Issue by Seiyaroo** [SeattleColleges/nsc-events-nextjs#52]
As a developer, I will want to create a user interface for updating an event.

Describe the solution you'd like
Create the user interface for updating an Events information in our application.

Include link(s) to relevant tutorial(s)
[NextJS Documentation](https://nextjs.org/learn/foundations/from-javascript-to-react/building-ui-with-components)
Collaborate with developer(s) creating other UI components

Is this issue related to any other issues?
TBD

Story Points
4-6

**Comment by taylorpapke** [comment]
This is an old issue which will be replaced with our new user story format.
