### ISSUE TITLE
BUG: Pronouns field is required but does not cause an error when left blank

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/nsc-events-nextjs#522]
The Pronouns field on the Sign Up page does not have an error when left blank, despite being a required field.

<img width="475" alt="image" src="https://github.com/SeattleColleges/nsc-events-nextjs/assets/77591083/b254a133-813c-47d1-add3-35950854320a">

**Comment by Asfand00** [comment]
@MuhammadNSC @heosman are you guys working on this issue as well? If so want to pair program? or do you have it figured out? Let me know if I can help or not, otherwise its cool and I can choose another issue, thanks

**Comment by JesseCaddell** [comment]
> @MuhammadNSC @heosman are you guys working on this issue as well? If so want to pair program? or do you have it figured out? Let me know if I can help or not, otherwise its cool and I can choose another issue, thanks 

Hey Ozzy, both of these students are not current in the practicum! Feel free to take this on if you'd like 😄

**Comment by Asfand00** [comment]
> > @MuhammadNSC @heosman are you guys working on this issue as well? If so want to pair program? or do you have it figured out? Let me know if I can help or not, otherwise its cool and I can choose another issue, thanks
> 
> Hey Ozzy, both of these students are not currently in the practicum! Feel free to take this on if you'd like 😄

oh, I see lol my bad for not checking properly (I was confused). I'll take this on. thanks @JesseCaddell
