### ISSUE TITLE
BUG: Unable to save changes for Date, Start time, & End time fields in Edit dialog

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/nsc-events-nextjs#525]
Tasks:

- [ ] When changes are made to the Event Date, Start Time, and End Time fields, the Confirm Edit button is still disabled.
- [ ] The Add Tag field is missing from the Edit Event dialog

**Comment by ken-ni** [comment]
Hello @heosman I can look into this.

**Comment by ken-ni** [comment]
Sorry, this issue is actually too difficult for me so I will be dropping it. Please feel free to pick up this issue.
