### ISSUE TITLE
Delete Event UI

### ISSUE THREAD

**Issue by Seiyaroo** [SeattleColleges/nsc-events-nextjs#53]
As a developer, I will want to create a user interface for deleting an Event.
The event will open appear as deleted to the user and creator. This is known as a "soft delete".
We can do this by adding a property to event title isDeleted. Then when a creator marks an event for deletion this property will be set to true. When displaying events we will filter out any where isDeleted is true.

Describe the solution you'd like
Create the user interface for deleting a Events information in our application.

Include link(s) to relevant tutorial(s)
[NextJS Documentation](https://nextjs.org/learn/foundations/from-javascript-to-react/building-ui-with-components)
Collaborate with developer(s) creating other UI components

Is this issue related to any other issues?
TBD

Story Points
4-6

**Comment by taylorpapke** [comment]
This is an old issue which will be replaced with our new user story format.
